name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - if: success()
      name: Send build success message
      uses: bencgreen/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Jeebs (GitHub)
        SLACK_MESSAGE: Build Succeeded
        SLACK_COLOR: good
        SLACK_ICON: https://bcgdesign.com/img/logo-square-580x580.png
    - if: failure()
      name: Send build fail message
      uses: bencgreen/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Jeebs (GitHub)
        SLACK_MESSAGE: Build Failed
        SLACK_COLOR: danger
        SLACK_ICON: https://bcgdesign.com/img/logo-square-580x580.png
    
