name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install dependencies
      run: dotnet restore BuildForTesting.csproj
    - name: Build
      run: dotnet build BuildForTesting.csproj --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-restore --no-build --configuration Release --verbosity normal
    - if: success()
      name: Pack NuGet packages
      run: dotnet pack BuildForPacking.csproj --no-build --configuration Release /p:PackageOutputPath=.nupkgs
    - if: success()
      name: Push NuGet packages
      run: dotnet nuget push .nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
    - if: success()
      name: Send success message
      uses: bencgreen/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Jeebs (GitHub)
        SLACK_MESSAGE: Publish Succeeded
        SLACK_COLOR: good
        SLACK_ICON: https://bcgdesign.com/img/logo-square-580x580.png
    - if: failure()
      name: Send fail message
      uses: bencgreen/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Jeebs (GitHub)
        SLACK_MESSAGE: Publish Failed
        SLACK_COLOR: danger
        SLACK_ICON: https://bcgdesign.com/img/logo-square-580x580.png
    
