name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  restore-build-test-pack-push:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Prepare - Checkout Code
      uses: actions/checkout@v2
    -
      name: Prepare - Read version
      uses: juliangruber/read-file-action@v1
      with:
        path: ./Version
      id: version
    - 
      name: Prepare - Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - 
      name: A - Restore
      run: dotnet restore Test.csproj
    - 
      name: B - Build
      run: dotnet build Test.csproj --no-restore -c Release
    #- 
    #  name: C - Test
    #  run: dotnet test Test.csproj --no-restore --no-build -c Release --verbosity normal
    - 
      if: success()
      name: D - Pack
      run: dotnet pack Pack.csproj --no-build -c Release /p:PackageOutputPath=$HOME/.nupkgs -p:PackageVersion=${{ steps.version.outputs.content }}
    - 
      if: success()
      name: E - Push
      run: dotnet nuget push "$HOME/.nupkgs/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
    - 
      if: success()
      name: Finish - Success
      uses: bencgreen/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Jeebs (GitHub)
        SLACK_MESSAGE: Publish Succeeded
        SLACK_COLOR: good
        SLACK_ICON: https://bcgdesign.com/img/logo-square-580x580.png
    - 
      if: failure()
      name: Finish - Failure
      uses: bencgreen/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Jeebs (GitHub)
        SLACK_MESSAGE: Publish Failed
        SLACK_COLOR: danger
        SLACK_ICON: https://bcgdesign.com/img/logo-square-580x580.png
    
